name: Build and publish add-on image

on:
  push:
    branches:
      - main
    paths:
      - "jeeves_agent/**"
      - ".github/workflows/build.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get add-on information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./jeeves_agent"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push add-on image
        uses: home-assistant/builder@master
        with:
          args: |
            --target /data/jeeves_agent \
            --generic ${{ steps.info.outputs.version }} \
            --docker-hub ghcr.io/bulldoguk
